 --- criteria and Sub criteria DB design ----- 
CREATE TABLE XXRTA_ASSESS_CRT_HDR_DEF
(
	ASSESS_CRITERIA_HDR_ID NUMBER, 
	ASSESSMENT_SCOPE_ID NUMBER, 
	RADAR_TYPE_ID NUMBER,  -- variable list LINE_ID
	ASSESS_CATEGORY_ID NUMBER, 
	ASSESS_SUBCATEGORY_ID NUMBER, 
	ASSESS_CRIT_CLASS_ID NUMBER,  -- variable list LINE_ID
	ASSESS_CRITERIA_PARENT NUMBER, 
	ASSESS_CRITERIA_NAME_EN VARCHAR2(500),
	ASSESS_CRITERIA_NAME_AR VARCHAR2(500),	
	ASSESS_CRITERIA_POINTS NUMBER, 
	ASSESS_CRITERIA_WTG NUMBER, 
	ASSESS_CRITERIA_DESC_EN VARCHAR2(3000), 
	ASSESS_CRITERIA_DESC_AR VARCHAR2(3000), 
	ASSESS_CRITERIA_VERSION NUMBER, 
	ASSESS_CRITERIA_ORDER NUMBER, 
	ASSESS_CRIT_STATUS VARCHAR2(2), 
	ASSESS_CRITERIA_OWNER NUMBER,  
	CREATION_DATE DATE, 
	CREATED_BY VARCHAR2(100),	
	LAST_UPDATED_BY VARCHAR2(100),		
	LAST_UPDATE_DATE DATE, 
	LAST_UPDATE_LOGIN NUMBER,
	VERSION_NUMBER NUMBER, 
	CHR_ATTRIBUTE1 VARCHAR2(250),
	CHR_ATTRIBUTE2 VARCHAR2(250),
	CHR_ATTRIBUTE3 VARCHAR2(250),
	CHR_ATTRIBUTE4 VARCHAR2(250),
	CHR_ATTRIBUTE5 VARCHAR2(250),
	CHR_ATTRIBUTE6 VARCHAR2(250),
	CHR_ATTRIBUTE7 VARCHAR2(250),
	CHR_ATTRIBUTE8 VARCHAR2(250),
	CHR_ATTRIBUTE9 VARCHAR2(250),
	CHR_ATTRIBUTE10 VARCHAR2(250),
	NUM_ATTRIBUTE1 NUMBER,
	NUM_ATTRIBUTE2 NUMBER,
	NUM_ATTRIBUTE3 NUMBER,
	NUM_ATTRIBUTE4 NUMBER,
	NUM_ATTRIBUTE5 NUMBER,
	DTE_ATTRIBUTE1 DATE,
	DTE_ATTRIBUTE2 DATE,
	DTE_ATTRIBUTE3 DATE,
	DTE_ATTRIBUTE4 DATE,
	DTE_ATTRIBUTE5 DATE,
        CONSTRAINT XXRTA_ASSESS_CATEGORY_DEF_PK PRIMARY KEY (ASSESS_CRITERIA_HDR_ID)
 );
 
 CREATE SEQUENCE  XXRTA_ASSESS_CRT_HDR_DEF_S START WITH 1000 INCREMENT BY 1 NOCACHE  NOORDER  NOCYCLE ;
 
CREATE SEQUENCE XXRTA_ASSESS_HDR_ORD_S ---- SEQUENCEfor Order number
		START WITH 100
		MAXVALUE 999999999999999999999999999
		MINVALUE 1
		NOCYCLE
		NOCACHE
		NOORDER;
		
 CREATE TABLE XXRTA_ASSESS_CRT_DOC_DTL
  (
    ASSESS_CRITERIA_HDR_ID  NUMBER,
    ASSESS_CRITERIA_DOC_ID  NUMBER,
    ASSESS_CRITERIA_DOCNAME VARCHAR2(240),
    CREATION_DATE DATE, 
	CREATED_BY VARCHAR2(100),	
	LAST_UPDATED_BY VARCHAR2(100),		
	LAST_UPDATE_DATE DATE, 
	LAST_UPDATE_LOGIN NUMBER,
	VERSION_NUMBER NUMBER,
	        CONSTRAINT XXRTA_ASSESS_CATEGORY_DEF_PK PRIMARY KEY (ASSESS_CRITERIA_DOC_ID)
  );
  
  CREATE SEQUENCE XXRTA_ASSESS_CRT_DOC_DTL_S
START WITH 1000
MAXVALUE 999999999999999999999999999
MINVALUE 1
NOCYCLE
NOCACHE
NOORDER;

  
   CREATE TABLE XXRTA_ASSESS_CRT_CONT_DTL
  (
    ASSESS_CRITERIA_HDR_ID   NUMBER ,
    ASSESS_CRITERIA_CONT_ID  NUMBER ,
    ASSESS_CRT_CONT_PER_NAME VARCHAR2(240) ,
    CREATION_DATE DATE, 
	CREATED_BY VARCHAR2(100),	
	LAST_UPDATED_BY VARCHAR2(100),		
	LAST_UPDATE_DATE DATE, 
	LAST_UPDATE_LOGIN NUMBER,
	VERSION_NUMBER NUMBER,s
		        CONSTRAINT XXRTA_ASSESS_CATEGORY_DEF_PK PRIMARY KEY (ASSESS_CRITERIA_CONT_ID)
  );
   
   CREATE SEQUENCE XXRTA_ASSESS_CRT_CONT_DTL_S
		START WITH 1000
		MAXVALUE 999999999999999999999999999
		MINVALUE 1
		NOCYCLE
		NOCACHE
		NOORDER;