  -- Category DB Design -------
CREATE TABLE XXRTA_ASSESS_CATEGORY_DEF
(
	ASSESS_CATEGORY_ID NUMBER, 
	ASSESSMENT_SCOPE_ID NUMBER, 
	CATEGORY_CLASS_ID NUMBER, -- variable list LINE_ID	
	ASSESS_CATEGORY_PARENT_ID NUMBER, 
	ASSESS_CATEGORY_NAME_EN VARCHAR2(2000),
	ASSESS_CATEGORY_NAME_AR VARCHAR2(2000), 
	ASSESS_CATEGORY_POINTS NUMBER, 
	ASSESS_CATEGORY_WTG NUMBER, 
	ASSESS_CATEGORY_DESC_EN VARCHAR2(2000),
	ASSESS_CATEGORY_DESC_AR VARCHAR2(2000), 
	ASSESS_CATEGORY_VERSION NUMBER, 
	ASSESS_CATEGORY_SCORE NUMBER, 
	ASSESS_CATEGORY_ORDER NUMBER, -- SEQUENCE
	ASSESS_CATEGORY_STATUS VARCHAR2(2), 
	CREATION_DATE DATE, 
	CREATED_BY VARCHAR2(100),	
	LAST_UPDATED_BY VARCHAR2(100),		
	LAST_UPDATE_DATE DATE, 
	LAST_UPDATE_LOGIN NUMBER,
	VERSION_NUMBER NUMBER, 
	CHR_ATTRIBUTE1 VARCHAR2(250),
	CHR_ATTRIBUTE2 VARCHAR2(250),
	CHR_ATTRIBUTE3 VARCHAR2(250),
	CHR_ATTRIBUTE4 VARCHAR2(250),
	CHR_ATTRIBUTE5 VARCHAR2(250),
	CHR_ATTRIBUTE6 VARCHAR2(250),
	CHR_ATTRIBUTE7 VARCHAR2(250),
	CHR_ATTRIBUTE8 VARCHAR2(250),
	CHR_ATTRIBUTE9 VARCHAR2(250),
	CHR_ATTRIBUTE10 VARCHAR2(250),
	NUM_ATTRIBUTE1 NUMBER,
	NUM_ATTRIBUTE2 NUMBER,
	NUM_ATTRIBUTE3 NUMBER,
	NUM_ATTRIBUTE4 NUMBER,
	NUM_ATTRIBUTE5 NUMBER,
	DTE_ATTRIBUTE1 DATE,
	DTE_ATTRIBUTE2 DATE,
	DTE_ATTRIBUTE3 DATE,
	DTE_ATTRIBUTE4 DATE,
	DTE_ATTRIBUTE5 DATE,
        CONSTRAINT XXRTA_ASSESS_CATEGORY_DEF_PK PRIMARY KEY (ASSESS_CATEGORY_ID)
 );
   
   CREATE SEQUENCE  XXRTA_ASSESS_CATEGORY_DEF_S START WITH 1000 INCREMENT BY 1 NOCACHE  NOORDER  NOCYCLE ; --  Order number SEQUENCE
